/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start OIDC Code + PKCE S256 login */
        get: operations["startLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consume one-time login flow; redirect to /projects or fixed error screen */
        get: operations["finishLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current principal; CSRF token null for Bearer */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invalidate local session; cookie and CSRF required */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List only visible projects */
        get: operations["listProjects"];
        put?: never;
        /** Create project and initial owner atomically */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read visible project */
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Owner-only paginated membership list; use access-policy resource for edits and ETag */
        get: operations["listMemberships"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Owner-only minimal audit records */
        get: operations["listAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List visible objects; default active */
        get: operations["listObjects"];
        put?: never;
        /** Create metadata and draft revision 1 atomically */
        post: operations["createObject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/objects/{object_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Object metadata with object ETag */
        get: operations["getObject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename/description change independent of definition digest */
        patch: operations["updateObjectMetadata"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/objects/{object_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read draft and its revision ETag */
        get: operations["getDraft"];
        /** Replace definition with semantic/project-reference validation */
        put: operations["replaceDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/objects/{object_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List immutable definition versions */
        get: operations["listVersions"];
        put?: never;
        /** Finalize draft; existing identical digest gives 200, new version 201 */
        post: operations["finalizeVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/objects/{object_id}/versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read immutable version; no write endpoint */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/objects/{object_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Owner-only active to archived, object ETag required */
        post: operations["archiveObject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/access-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Owner-only complete access policy, at most 100 members, strong ACL ETag */
        get: operations["getAccessPolicy"];
        /** Owner-only atomic replacement of access policy; at least one active owner; no duplicate principals */
        put: operations["replaceAccessPolicy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Definition: components["schemas"]["definitions.schema"];
        ProjectCreate: {
            name: string;
            description: string;
        };
        Project: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            acl_revision: number;
            /** Format: uuid */
            created_by: string;
            /** Format: date-time */
            created_at: string;
            /** @enum {unknown} */
            my_role: "reader" | "editor" | "owner";
        };
        Membership: {
            /** Format: uuid */
            project_id: string;
            /** Format: uuid */
            principal_id: string;
            /** @enum {unknown} */
            role: "reader" | "editor" | "owner";
            /** Format: date-time */
            created_at: string;
        };
        ObjectCreate: {
            name: string;
            description: string;
            definition: components["schemas"]["definitions.schema"];
        };
        MetadataPatch: {
            name?: string;
            description?: string;
        };
        Object: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            /** @enum {unknown} */
            kind: "dataset" | "transformation";
            name: string;
            description: string;
            /** @enum {unknown} */
            state: "active" | "archived";
            draft_revision: number;
            /** Format: uuid */
            latest_version_id: string | null;
            /** Format: uuid */
            created_by: string;
            /** Format: date-time */
            created_at: string;
            revision: number;
        };
        DraftWrite: {
            definition: components["schemas"]["definitions.schema"];
        };
        Draft: {
            /** Format: uuid */
            project_id: string;
            /** Format: uuid */
            object_id: string;
            revision: number;
            definition: components["schemas"]["definitions.schema"];
            /** Format: uuid */
            updated_by: string;
            /** Format: date-time */
            updated_at: string;
        };
        Version: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            /** Format: uuid */
            object_id: string;
            number: number;
            digest: string;
            definition: components["schemas"]["definitions.schema"];
            /** Format: uuid */
            created_by: string;
            /** Format: date-time */
            created_at: string;
        };
        Session: {
            /** Format: uuid */
            principal_id: string;
            display_name: string;
            can_create_project: boolean;
            csrf_token: string | null;
        };
        Audit: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            /** Format: uuid */
            actor_id: string;
            action: string;
            /** Format: uuid */
            target_id: string;
            /** Format: uuid */
            version_id: string | null;
            /** @enum {unknown} */
            outcome: "allowed" | "denied";
            /** Format: date-time */
            occurred_at: string;
            /** Format: uuid */
            request_id: string;
        };
        Problem: {
            type: string;
            title: string;
            status: number;
            code: string;
            /** Format: uuid */
            request_id: string;
            errors?: {
                pointer: string;
                code: string;
            }[];
        };
        ProjectPage: {
            items: components["schemas"]["Project"][];
            next_cursor: string | null;
        };
        ObjectPage: {
            items: components["schemas"]["Object"][];
            next_cursor: string | null;
        };
        VersionPage: {
            items: components["schemas"]["Version"][];
            next_cursor: string | null;
        };
        MembershipPage: {
            items: components["schemas"]["Membership"][];
            next_cursor: string | null;
        };
        AuditPage: {
            items: components["schemas"]["Audit"][];
            next_cursor: string | null;
        };
        AccessPolicyWrite: {
            members: {
                /** Format: uuid */
                principal_id: string;
                /** @enum {unknown} */
                role: "reader" | "editor" | "owner";
            }[];
        };
        AccessPolicy: {
            /** Format: uuid */
            project_id: string;
            revision: number;
            members: {
                /** Format: uuid */
                principal_id: string;
                /** @enum {unknown} */
                role: "reader" | "editor" | "owner";
            }[];
        };
        ParameterValue: string | boolean | number;
        Parameters: {
            [key: string]: components["schemas"]["ParameterValue"];
        };
        FileSource: {
            /** @constant */
            connector: "file";
            /** @enum {unknown} */
            format: "csv" | "parquet";
            binding: string;
        };
        SqlSource: {
            /** @constant */
            connector: "postgresql";
            connection_binding: string;
            query: string;
            parameters: components["schemas"]["Parameters"];
        };
        PythonImplementation: {
            /** @constant */
            language: "python";
            module: string;
            callable: string;
        };
        SqlImplementation: {
            /** @constant */
            language: "sql";
            query: string;
            connection_binding: string;
        };
        InputPort: {
            name: string;
            /** @constant */
            data_kind: "tabular";
            /** Format: uuid */
            dataset_object_id?: string;
        };
        OutputPort: {
            name: string;
            /** @constant */
            data_kind: "tabular";
        };
        DatasetDefinition: {
            /** @constant */
            schema_version: "1.0";
            /** @constant */
            kind: "dataset";
            source: components["schemas"]["FileSource"] | components["schemas"]["SqlSource"];
        };
        TransformationDefinition: {
            /** @constant */
            schema_version: "1.0";
            /** @constant */
            kind: "transformation";
            implementation: components["schemas"]["PythonImplementation"] | components["schemas"]["SqlImplementation"];
            inputs: components["schemas"]["InputPort"][];
            outputs: components["schemas"]["OutputPort"][];
            parameters: components["schemas"]["Parameters"];
        };
        /** Torii SPEC-0001 definition contract, revision 0.2 (In review) */
        "definitions.schema": {
            $defs: {
                ParameterValue: string | boolean | number;
                Parameters: {
                    [key: string]: components["schemas"]["ParameterValue"];
                };
                InputPort: {
                    name: string;
                    /** @constant */
                    data_kind: "tabular";
                    /** Format: uuid */
                    dataset_object_id?: string;
                };
                OutputPort: {
                    name: string;
                    /** @constant */
                    data_kind: "tabular";
                };
                FileSource: {
                    /** @constant */
                    connector: "file";
                    /** @enum {unknown} */
                    format: "csv" | "parquet";
                    binding: string;
                };
                SqlSource: {
                    /** @constant */
                    connector: "postgresql";
                    connection_binding: string;
                    query: string;
                    parameters: components["schemas"]["Parameters"];
                };
                PythonImplementation: {
                    /** @constant */
                    language: "python";
                    module: string;
                    callable: string;
                };
                SqlImplementation: {
                    /** @constant */
                    language: "sql";
                    query: string;
                    connection_binding: string;
                };
                DatasetDefinition: {
                    /** @constant */
                    schema_version: "1.0";
                    /** @constant */
                    kind: "dataset";
                    source: components["schemas"]["FileSource"] | components["schemas"]["SqlSource"];
                };
                TransformationDefinition: {
                    /** @constant */
                    schema_version: "1.0";
                    /** @constant */
                    kind: "transformation";
                    implementation: components["schemas"]["PythonImplementation"] | components["schemas"]["SqlImplementation"];
                    inputs: components["schemas"]["InputPort"][];
                    outputs: components["schemas"]["OutputPort"][];
                    parameters: components["schemas"]["Parameters"];
                };
            };
        } & (components["schemas"]["DatasetDefinition"] | components["schemas"]["TransformationDefinition"]);
    };
    responses: {
        /** @description Problem Details; no sensitive values. See access-and-api.md for semantics and authorization ordering. */
        Problem: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                "Cache-Control"?: "no-store";
                /** @description Required for 429 and retryable 503; omitted otherwise. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        ProjectId: string;
        ObjectId: string;
        VersionId: string;
        Limit: number;
        /** @description Signed opaque cursor, TTL 15 min, actor/scope/filter-bound; invalid returns generic 400. */
        Cursor: string;
        /** @description Literal case-insensitive name substring; authorization precedes filtering. */
        Query: string;
        /** @description One strong resource-specific ETag. Missing 428, malformed 400, stale 412. */
        IfMatch: string;
        /** @description UUIDv4, scoped to actor/operation/project (organization for project creation), TTL 24 h. */
        Idempotency: string;
        /** @description REQUIRED for cookie-authenticated mutations, not for Bearer without cookie; matching Origin is also required. */
        Csrf: string;
    };
    requestBodies: never;
    headers: {
        RequestId: string;
        ETag: string;
        Location: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    startLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            303: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    "Cache-Control"?: "no-store";
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    finishLogin: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            303: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    "Cache-Control"?: "no-store";
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: {
                /** @description REQUIRED for cookie-authenticated mutations, not for Bearer without cookie; matching Origin is also required. */
                "X-CSRF-Token"?: components["parameters"]["Csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            204: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listProjects: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                /** @description Signed opaque cursor, TTL 15 min, actor/scope/filter-bound; invalid returns generic 400. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Literal case-insensitive name substring; authorization precedes filtering. */
                q?: components["parameters"]["Query"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header: {
                /** @description UUIDv4, scoped to actor/operation/project (organization for project creation), TTL 24 h. */
                "Idempotency-Key": components["parameters"]["Idempotency"];
                /** @description REQUIRED for cookie-authenticated mutations, not for Bearer without cookie; matching Origin is also required. */
                "X-CSRF-Token"?: components["parameters"]["Csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful response */
            201: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    "Cache-Control"?: "no-store";
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listMemberships: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                /** @description Signed opaque cursor, TTL 15 min, actor/scope/filter-bound; invalid returns generic 400. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipPage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listAudit: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                /** @description Signed opaque cursor, TTL 15 min, actor/scope/filter-bound; invalid returns generic 400. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listObjects: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                /** @description Signed opaque cursor, TTL 15 min, actor/scope/filter-bound; invalid returns generic 400. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Literal case-insensitive name substring; authorization precedes filtering. */
                q?: components["parameters"]["Query"];
                kind?: "dataset" | "transformation";
                state?: "active" | "archived" | "all";
            };
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectPage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    createObject: {
        parameters: {
            query?: never;
            header: {
                /** @description UUIDv4, scoped to actor/operation/project (organization for project creation), TTL 24 h. */
                "Idempotency-Key": components["parameters"]["Idempotency"];
                /** @description REQUIRED for cookie-authenticated mutations, not for Bearer without cookie; matching Origin is also required. */
                "X-CSRF-Token"?: components["parameters"]["Csrf"];
            };
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObjectCreate"];
            };
        };
        responses: {
            /** @description Successful response */
            201: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    "Cache-Control"?: "no-store";
                    Location: components["headers"]["Location"];
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Object"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getObject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                object_id: components["parameters"]["ObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    "Cache-Control"?: "no-store";
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Object"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    updateObjectMetadata: {
        parameters: {
            query?: never;
            header: {
                /** @description One strong resource-specific ETag. Missing 428, malformed 400, stale 412. */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description REQUIRED for cookie-authenticated mutations, not for Bearer without cookie; matching Origin is also required. */
                "X-CSRF-Token"?: components["parameters"]["Csrf"];
            };
            path: {
                project_id: components["parameters"]["ProjectId"];
                object_id: components["parameters"]["ObjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MetadataPatch"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    "Cache-Control"?: "no-store";
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Object"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                object_id: components["parameters"]["ObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    "Cache-Control"?: "no-store";
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    replaceDraft: {
        parameters: {
            query?: never;
            header: {
                /** @description One strong resource-specific ETag. Missing 428, malformed 400, stale 412. */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description REQUIRED for cookie-authenticated mutations, not for Bearer without cookie; matching Origin is also required. */
                "X-CSRF-Token"?: components["parameters"]["Csrf"];
            };
            path: {
                project_id: components["parameters"]["ProjectId"];
                object_id: components["parameters"]["ObjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftWrite"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    "Cache-Control"?: "no-store";
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listVersions: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                /** @description Signed opaque cursor, TTL 15 min, actor/scope/filter-bound; invalid returns generic 400. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                object_id: components["parameters"]["ObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionPage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    finalizeVersion: {
        parameters: {
            query?: never;
            header: {
                /** @description One strong resource-specific ETag. Missing 428, malformed 400, stale 412. */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description UUIDv4, scoped to actor/operation/project (organization for project creation), TTL 24 h. */
                "Idempotency-Key": components["parameters"]["Idempotency"];
                /** @description REQUIRED for cookie-authenticated mutations, not for Bearer without cookie; matching Origin is also required. */
                "X-CSRF-Token"?: components["parameters"]["Csrf"];
            };
            path: {
                project_id: components["parameters"]["ProjectId"];
                object_id: components["parameters"]["ObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    "Cache-Control"?: "no-store";
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
            /** @description Successful response */
            201: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    "Cache-Control"?: "no-store";
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
                object_id: components["parameters"]["ObjectId"];
                version_id: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    archiveObject: {
        parameters: {
            query?: never;
            header: {
                /** @description One strong resource-specific ETag. Missing 428, malformed 400, stale 412. */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description UUIDv4, scoped to actor/operation/project (organization for project creation), TTL 24 h. */
                "Idempotency-Key": components["parameters"]["Idempotency"];
                /** @description REQUIRED for cookie-authenticated mutations, not for Bearer without cookie; matching Origin is also required. */
                "X-CSRF-Token"?: components["parameters"]["Csrf"];
            };
            path: {
                project_id: components["parameters"]["ProjectId"];
                object_id: components["parameters"]["ObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    "Cache-Control"?: "no-store";
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Object"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getAccessPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    "Cache-Control"?: "no-store";
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessPolicy"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    replaceAccessPolicy: {
        parameters: {
            query?: never;
            header: {
                /** @description One strong resource-specific ETag. Missing 428, malformed 400, stale 412. */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description UUIDv4, scoped to actor/operation/project (organization for project creation), TTL 24 h. */
                "Idempotency-Key": components["parameters"]["Idempotency"];
                /** @description REQUIRED for cookie-authenticated mutations, not for Bearer without cookie; matching Origin is also required. */
                "X-CSRF-Token"?: components["parameters"]["Csrf"];
            };
            path: {
                project_id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccessPolicyWrite"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    "Cache-Control"?: "no-store";
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessPolicy"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            412: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
}
